### ISSUE TITLE
Transcripts are all one person

### ISSUE THREAD

**Issue by patricknelson** [syntaxfm/website#1562] opened 2024-02-18 21:51 UTC
E.g. This one shows only Scott: https://syntax.fm/show/727/how-to-code-opinionated-typescript-stack-tooling-choices-explained/transcript

This one shows only Wes: https://syntax.fm/show/726/is-htmx-a-joke/transcript

In case it’s just me, I’m on iPadOS 17.2 (11-inch 3rd gen)

**Comment by wesbos** [comment] 2024-02-20 22:56
Thanks - duplicate of https://github.com/syntaxfm/website/issues/1193 

something is going  on with the regex - will dig in..

**Closed** 2024-02-20 22:57 UTC
